---
title: "Analysis Monitor"
id: chapter-AnalysisMonitor
editor: source
---
  
```{r}
#| label: Setup
#| echo: false
#| include: false

knitr::opts_chunk$set(echo = FALSE)

#SiteName <- "Frankfurt"

source("RSetup.R")

```

\

### Harmonization Monitors

```{r}
#| label: TransformationMonitors
#| warning: false

load("TransformationMonitor.rda")

ls_Tables <- map(TransformationMonitor,
                 function(MonitorDF)
                 {
                     if (!is.null(MonitorDF))
                     {
                         MonitorDF %>%
                             gt(groupname_col = "Feature") %>%
                             dsCCPhosClient::gtTheme_CCP(TableAlign = "left", ShowNAs = TRUE, TableWidth = "80%") %>%
                             tab_style(locations = cells_body(rows = (Value != "NA" & IsValueEligible == TRUE & Final > 0)),
                                       style = cell_fill(color = "green")) %>%
                             tab_style(locations = cells_body(rows = (Value != "NA" & IsValueEligible == TRUE & Final == 0)),
                                       style = cell_fill(color = "lightgreen")) %>%
                             tab_style(locations = cells_body(rows = (Value == "NA" | is.na(Value))),
                                       style = cell_fill(color = "gray")) %>%
                             tab_style(locations = cells_body(columns = c(Value, IsValueEligible, Transformed),
                                                              rows = (Value != "NA" & IsValueEligible == FALSE & Transformed > 0 & Final == 0)),
                                       style = cell_fill(color = "red")) %>%
                             tab_style(locations = cells_body(columns = c(Value, IsValueEligible, Raw, Transformed),
                                                              rows = (Value != "NA" & IsValueEligible == FALSE & Raw > 0 & Transformed == 0)),
                                       style = cell_fill(color = "orange"))
                     }
                 })

ls_Tables[[1]]

ls_Tables[[2]]

ls_Tables[[3]]

ls_Tables[[4]]

ls_Tables[[5]]

ls_Tables[[6]]

ls_Tables[[7]]

ls_Tables[[8]]

ls_Tables[[9]]


```

